name: Push-to-EC2
# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout the code
        uses: actions/checkout@v2

      # Step 2: Deploy files to EC2 server using SSH
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      # Step 3: Execute remote commands on EC2
      - name: Run commands on EC2 server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update packages
            sudo apt-get -y update

            # Install and start Apache if not already installed
            if ! command -v apache2 &> /dev/null; then
              sudo apt-get install -y apache2
              sudo systemctl enable apache2
            fi
            sudo systemctl restart apache2
            
            # Move application files to web directory
            sudo rm -rf /var/www/html/*
            sudo cp -r ${{ secrets.TARGET_DIR }}/* /var/www/html/
            sudo chown -R www-data:www-data /var/www/html/
